Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'domain/spec/**/*'
AllCops:
  Exclude:
    - 'bin/**'
    - 'lib/tasks/cucumber.rake'
    - 'db/schema.rb'
    - 'script/cucumber'
    - 'Gemfile'
